theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: teal
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/server
    repo: material/github
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - content.code.annotate
    - search.suggest

plugins:
  - meta
  - search
  - privacy
  - social
  - tags:
      tags_file: tags.md
  - blog:
      post_url_date_format: yyyy/MM
      categories_allowed:
        - Advent of Code
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: timeago
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes
  - tables

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

site_name: bootleg.technology
site_url: https://bootleg.technology
repo_url: https://github.com/nint8835/bootleg.technology
repo_name: nint8835/bootleg.technology
edit_uri: edit/main/docs/
extra:
  social:
    - icon: material/mastodon
      link: https://hachyderm.io/@nit
    - icon: material/github
      link: https://github.com/nint8835
copyright: Copyright &copy; 2023 Riley Flynn

nav:
  - Home: index.md
  - Blog:
      - blog/index.md
  - Homelab:
    - Cluster:
      - Guides:
        - Adding a Node: homelab/cluster/guides/adding-a-node.md
        - Adding a Host: homelab/cluster/guides/adding-a-host.md
