theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: teal
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/server
    repo: material/github
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - content.tabs.link

plugins:
  - search
  - privacy
  - social
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - meta

site_name: bootleg.technology
site_url: https://bootleg.technology
repo_url: https://github.com/nint8835/bootleg.technology
repo_name: nint8835/bootleg.technology
edit_uri: edit/main/docs/
extra:
  social:
    - icon: material/twitter
      link: https://twitter.com/bootlegjohn
    - icon: material/github
      link: https://github.com/nint8835
copyright: Copyright &copy; 2022 Riley Flynn
